version: '3'

x-timezone-env: &timezone-env
    TZ: "America/Sao_Paulo"

x-db-env: &db-env
    MYSQL_ROOT_PASSWORD: "root"
    MYSQL_DATABASE: "m2"
    MYSQL_USER: "m2"
    MYSQL_PASSWORD: "12345678"

networks:
  m2-network:
    driver: bridge

services:
    nginx:
        container_name: m2-nginx
        image: nginx:latest
        working_dir: /var/www/html
        environment:
            << : *timezone-env
        depends_on:
            - phpfpm
        ports:
            - '8080:80'
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/logs/access.log:/var/log/nginx/access.log
            - ./docker/logs/error.log:/var/log/nginx/error.log
        restart: always
        networks:
            - m2-network

    phpfpm:
        container_name: m2-php
        build:
            args:
                user: m2
                uid: 1000
            context: .
            dockerfile: ./docker/php/Dockerfile
        image: dev/php
        environment:
            << : *timezone-env
        depends_on:
            - db
        volumes:
            - ./:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        restart: always
        networks:
            - m2-network

    db:
        container_name: m2-mysql
        image: mysql:8
        ports:
            - '3307:3306'
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/config-file.cnf
        working_dir: /var/lib/mysql
        environment:
            << : *timezone-env
            << : *db-env
        restart: on-failure
        networks:
            - m2-network
